apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: sphere.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/wallet/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: wallet-srv
                port:
                  number: 3000
          - path: /api/orders/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: order-srv
                port:
                  number: 3000
          - path: /api/stocks/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: stock-srv
                port:
                  number: 3000
          - path: /api/portfolio/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: portfolio-srv
                port:
                  number: 3000
          - path: /api/tradeengine/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tradeengine-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000